name: pandoc
version: '2.19'
summary: Universal markup converter
website: https://pandoc.org
description: |
  Pandoc is a Haskell library for converting from one markup format to another,
  and a command-line tool that uses this library.

compression: lzo

confinement: devmode # use 'strict' once you have the right plugs and slots

base: core20

parts:
  pandoc:
    plugin: nil
    build-packages: [haskell-platform]
    override-build: |
      snapcraftctl build
      cabal update
      cabal install pandoc
